### ISSUE TITLE
Cannot build in STM32CubeIDE

### ISSUE THREAD

**Issue by dizcza** [shuai132/ScopeMCU#10]
When I import as an existing project and click Build:

```
**** Build of configuration Debug for project ScopeMCU ****

Nothing to build for project ScopeMCU
```

I tried re-generating the project with CubeMX. No luck.

Ubuntu 22.04 LTS
STM32CubeIDE version: 1.10.1

**Comment by shuai132** [comment]
have you clone the submodules?
like: `git clone --recurse-submodules`

**Comment by shuai132** [comment]
I see, STM32CubeIDE is not support.
this project can only build by CMake(or some IDE support CMake) for now.


IDE config here: https://blog.csdn.net/u012456479/article/details/101543344

**Comment by dizcza** [comment]
I thought since you have an .ioc file you support official CubeIDE.
The link you posted describes Clion, as far as I could understand.

All right.

**Comment by shuai132** [comment]
You can just use cmake (after install requirements).

**Comment by dizcza** [comment]
That would be hard for me. Compiling in a terminal is not a big deal, but understanding the code... I got used to navigation and code jumps in IDEs.

**Comment by shuai132** [comment]
Yes, CMake only for build. 

when CMake ready, you can use CLion or VSCode.

**Comment by dizcza** [comment]
Ah OK, VSCode is an option then. Thanks.
