### ISSUE TITLE
最高采样率能达到1M吗

### ISSUE THREAD

**Issue by cdhigh** [shuai132/ScopeMCU#3]
我看说明里面特别指出

为了采样精度和校准，当前最高采样率: 70ksps

这个限制是在那实现的，如果不考虑精度，只是要看个大概，能否达到1M?
如何修改?

**Comment by shuai132** [comment]
1.多了个内部通道
2.采样周期比较长现在
3.采样结束有一些运算现在(DMA单次中断)


改起来麻烦

---原始邮件---
发件人: "cdhigh"<notifications@github.com&gt;
发送时间: 2020年10月30日(周五) 上午7:21
收件人: "shuai132/ScopeMCU"<ScopeMCU@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [shuai132/ScopeMCU] 最高采样率能达到1M吗 (#3)




 
我看说明里面特别指出
 
为了采样精度和校准，当前最高采样率: 70ksps
 
这个限制是在那实现的，如果不考虑精度，只是要看个大概，能否达到1M?
 如何修改?
