### ISSUE TITLE
STM32F4 CDC 不能发送到ScopeGUI，与编译器有关？

### ISSUE THREAD

**Issue by RadioOperator** [shuai132/ScopeMCU#4]
楼主您好，
我尝试移植F4的代码到我的F407板子上面，结果遇到了问题。
1. 编译通过，ADC工作正常，VCP（CDC）串口也有了，可是ScopeGUI打不开VCP，当然也收不到数据。
2. 检查发现，用其他终端软件也打不开这个VCP，当然也收不到数据。
3. 进一步检查后发现，可能与编译器有关。      为了找问题，我单独开了一个CDC工程，同一套代码在MDK和CLion（Win10）下面都能正常编译，但是CLion出来的代码就发生CDC不正常，与上面说的一样，PC终端软件收不到CDC_TransmitFS发送的打印内容。 而MDK编译出来的就正常。
同时，我Win10电脑的CLion系统，编译F103的那一套ScopeMCU（master）代码就全部工作正常。 我的CubeMX也是最新版本。

您遇到过这种问题吗？谢谢。

**Comment by shuai132** [comment]
我没有遇到过这种问题，401的分支我也测过是可以的。
1. 这可能说明VCP在STM32运行有问题。
2. 同上
3. 这看上去可能是407库和工程的问题了吧，，，您再检查一下如果解决了请告知一下~

**Comment by RadioOperator** [comment]
您原来的工程是用CubeMXv4.27+F4v1.21开的，我用目前最新版本的CubeMX才有了问题。
希望您能有时间，将代码更新到最新的CubeMX（v6.1.1)和FW_F4_v1.25.2，谢谢。

**Comment by RadioOperator** [comment]
解决不了，暂时放弃，等以后有时间再看看。
