### ISSUE TITLE
Is it possible to change PA0 to PB0 or any analog pins?

### ISSUE THREAD

**Issue by melehin** [shuai132/ScopeMCU#5]
Hi!

Thanks for your project! It works great.
I burned my PA0 input and trying to remap any analog pins but don't know how to do it :)

**Comment by shuai132** [comment]
1. The simplest way is using CubeMX(just open `ScopeMCU.ioc`), and you will see which pin can remap, just click and chose it!
2. In another way, open the file `Src/adc.c`, modify Pin and Channel according to datasheet.

**Comment by melehin** [comment]
@shuai132
Many thanks!
