### ISSUE TITLE
Clion 2021.2.3 

### ISSUE THREAD

**Issue by jixishi** [shuai132/ScopeMCU#6]
Scanning dependencies of target ScopeMCU.elf
[ 23%] Building C object CMakeFiles/ScopeMCU.elf.dir/App/retarget.c.obj
[ 25%] Building C object CMakeFiles/ScopeMCU.elf.dir/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal.c.obj
[ 26%] Building C object CMakeFiles/ScopeMCU.elf.dir/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc.c.obj
[ 28%] Building C object CMakeFiles/ScopeMCU.elf.dir/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_adc_ex.c.obj
[ 30%] Building C object CMakeFiles/ScopeMCU.elf.dir/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_cortex.c.obj
[ 32%] Building C object CMakeFiles/ScopeMCU.elf.dir/Drivers/STM32F1xx_HAL_Driver/Src/stm32f1xx_hal_dma.c.obj
<command-line>: error: expected identifier or '(' before string constant
I:\STM32H7\clion\stm32\ScopeMCU\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal.c:200:1: note: in expansion of macro '__weak'
  200 | __weak void HAL_MspInit(void)
      | ^~~~~~
<command-line>: error: expected identifier or '(' before string constant
I:\STM32H7\clion\stm32\ScopeMCU\Drivers\STM32F1xx_HAL_Driver\Src\stm32f1xx_hal.c:211:1: note: in expansion of macro '__weak'
  211 | __weak void HAL_MspDeInit(void)
      | ^~~~~~
<command-line>: error: expected identifier or '(' before string constant

**Comment by shuai132** [comment]
1. 和CLion无关
2. 应该编译器没有设置正确
