### ISSUE TITLE
1MSa possible?

### ISSUE THREAD

**Issue by dizcza** [shuai132/ScopeMCU#9]
The GUI does not allow setting the sampling frequency larger than 70kHz. And I see that the picture is breaking already at 70kHz.

But I did see others are using an STM32F103-based oscilloscope to get 1MSa sampling rate. Is it possible to achieve this with built-in ADC only? Or USB communication limits the speed to be lower than 70kHz? Will the situation improve if I switch to STM32F429 Discovery board with a (presumably) better ADC?

**Comment by shuai132** [comment]
same as another issue: #3


The current design limits the sampling rate for the following reasons/for specific purposes:
1. Multiple internal channels are used.
2. For accuracy, the sampling period is relatively long.
3. At the end of sampling (DMA single interrupt), some operations are used to realize triggering and other modes. This is also for portability without excessive use of hardware features.

If the above goals are abandoned, 1Msps can be achieved.

In addition, F4 can indeed have a higher sampling rate. See branch: `board/stm32f401`

**Comment by shuai132** [comment]
BTW, The GUI will auto fit hardware.

**Comment by dizcza** [comment]
Thanks for the description.

> Multiple internal channels are used.

Is that so? The UI is for one ADC channel. Do you mean you use several hardware ADCs to speedup/make accurate measurements and yet show as a single value?

I'd like to have an option in GUI to send a command to the board to turn on and off 1MSa mode. Consider this as a feature request.

In either case, the setup of your project is easy and I got my F103-based oscilloscope running under Linux which is great.

**Comment by shuai132** [comment]
You are right! we use an internal channel to correct the value of ADC pin. And use a larger adc sample cycle, which means adc will slower.

1Msps is possible, if we redesign some logic. But, I don't have much time now.
And, I fond there have many product which cheap enough now, so, this project don't want pay much time for performance.

**Comment by dizcza** [comment]
All right.
